
    Include('c25_ProgramHandlerClass.inc'),Once

c25_GlobalDataClass                                                     Class(),type, Module('c25_GlobalDataClass.clw'), Link('c25_GlobalDataClass.clw',1),DLL(0)
Construct                                                                   Procedure()
Destruct                                                                    Procedure()

ProgramHandlerClass                                                         &c25_ProgramHandlerClass

SystemClassesFlat                                                           &SystemClassesFlat_TYPE
SystemClasses                                                               &SystemClasses_TYPE
                                                                        End


