Include('c25_ProgramHandlerClass.inc'),Once

c25_GraphicsClass                                       Class(),type, Module('c25_GraphicsClass.clw'), Link('c25_GraphicsClass.clw',_ABCLinkMode_),DLL(_ABCDllMode_)

Construct                                                   Procedure()
Destruct                                                    Procedure()

ProgramHandler                                              &c25_ProgramHandlerClass()


                                        End

