    Include('c25_ProgramHandlerClass.inc'),Once

c25_SqliteClass_NavigationTree                                              Class(),Type, Module('c25_SqliteClass_NavigationTree.clw'), Link('c25_SqliteClass_NavigationTree.clw',1),DLL(0)

Construct                                                                       Procedure()
Destruct                                                                        Procedure()

ClassTypeName                                                                   cstring(128)
ProgramHandlerClass                                                             &c25_ProgramHandlerClass
NavigationTree                                                                  &NavigationTree_TYPE
SqliteClass                                                                     &c25_SqliteClass
                                                                            End


