    Include('c25_ProgramHandlerClass.inc'),Once

c25_SqliteColumnClass                                                      Class(),type, Module('c25_SqliteColumnClass.clw'), Link('c25_SqliteColumnClass.clw',1),DLL(0)
Construct                                                                       Procedure()
Destruct                                                                        Procedure()

ProgramHandlerClass                                                             &c25_ProgramHandlerClass
BitConverterClass                                                               &c25_BitConverterClass
Init                                                                            Procedure(),Long,proc

                                                                            End

