Include('c25_ProgramHandlerClass.inc'),Once

c25_DataSetClass           	                                            Class(),type,Module('c25_DataSetClass.clw'), Link('c25_DataSetClass.clw',_ABCLinkMode_),DLL(_ABCDllMode_)
Construct                                                                   Procedure()
Destruct                                                                    Procedure()

ClassTypeName                                                               cstring(128)
ProgramHandlerClass                                                         &c25_ProgramHandlerClass
                                                                        End


